/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DownloadDiag.java
 *
 * Created on Sep 17, 2011, 2:51:00 AM
 */
package GUI;

import downloadmanager.Download;
import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rayat
 */
public class DownloadDiag extends javax.swing.JDialog implements Observer {

    /** Creates new form DownloadDiag */
    private Download download;

    public DownloadDiag(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("IUT DOWNLOAD MANAGER v1.0");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        SizeLabel = new javax.swing.JLabel();
        DownloadedLable = new javax.swing.JLabel();
        SpeedLabel = new javax.swing.JLabel();
        TimeLabel = new javax.swing.JLabel();
        DownloadProgressBar = new javax.swing.JProgressBar(0,100);
        OpenButton = new javax.swing.JButton();
        ResumeButton = new javax.swing.JButton();
        PauseButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        OpenFolderButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        URLTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Status");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("File Size");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Downloaded");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Speed");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Time Left");

        StatusLabel.setText("Connecting");

        SizeLabel.setText("(Unknown)");

        DownloadedLable.setText("0");

        SpeedLabel.setText("0 KB");

        OpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/openfiles (Custom).jpg"))); // NOI18N
        OpenButton.setText("Open File");
        OpenButton.setEnabled(false);
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });

        ResumeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Play-Hot-icon (Custom).png"))); // NOI18N
        ResumeButton.setText("Resume");
        ResumeButton.setEnabled(false);
        ResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeButtonActionPerformed(evt);
            }
        });

        PauseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pause (Custom).jpg"))); // NOI18N
        PauseButton.setText("Pause");
        PauseButton.setEnabled(false);
        PauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseButtonActionPerformed(evt);
            }
        });

        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Stop-Normal-Red-icon (Custom).png"))); // NOI18N
        CancelButton.setText("Stop");
        CancelButton.setEnabled(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        OpenFolderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images (Custom).jpg"))); // NOI18N
        OpenFolderButton.setText("Open Foder");
        OpenFolderButton.setEnabled(false);
        OpenFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFolderButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("URL");

        URLTextField.setBackground(new java.awt.Color(223, 222, 222));
        URLTextField.setEditable(false);
        URLTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        URLTextField.setSelectedTextColor(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DownloadedLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(URLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(OpenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ResumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(PauseButton)
                        .addGap(18, 18, 18)
                        .addComponent(CancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DownloadProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(315, Short.MAX_VALUE)
                        .addComponent(OpenFolderButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CancelButton, OpenButton, PauseButton, ResumeButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(URLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(StatusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SizeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DownloadedLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SpeedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DownloadProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OpenFolderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenButton)
                    .addComponent(CancelButton)
                    .addComponent(PauseButton)
                    .addComponent(ResumeButton))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeButtonActionPerformed
        // TODO add your handling code here:
        resume();
    }//GEN-LAST:event_ResumeButtonActionPerformed

    private void PauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseButtonActionPerformed
        // TODO add your handling code here:
        pause();
    }//GEN-LAST:event_PauseButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        cancel();
        this.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OpenFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFolderButtonActionPerformed
        // TODO add your handling code here:
        OpenFolder();
    }//GEN-LAST:event_OpenFolderButtonActionPerformed

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        // TODO add your handling code here:
        OpenFile();
    }//GEN-LAST:event_OpenButtonActionPerformed
    private void resume() {
        download.resume();
    }

    private void pause() {
        download.pause();
    }

    private void cancel() {
        download.cancel();
    }

    private void OpenFolder() {
        Runtime rt = Runtime.getRuntime();
        String destination = "explorer " + download.getSAVEDIR();
        System.out.println(destination);
        try {
            Process p = rt.exec(destination);
        } catch (IOException ex) {
            Logger.getLogger(DownloadManagerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void OpenFile() {
        Runtime rt = Runtime.getRuntime();
        String dest = download.getSAVEDIR();
        if (dest.length() == 3) {
            dest = dest.substring(0, 2);
            System.out.println(dest);
        }
        String destination = "explorer " + dest;
        String fileName = download.getFILENAME();
        fileName = fileName.substring(fileName.lastIndexOf('/') + 1);
        System.out.println(fileName);
        destination = destination + File.separator + fileName;
        System.out.println(destination);
        try {
            Process p = rt.exec(destination);
        } catch (IOException ex) {
            Logger.getLogger(DownloadManagerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DownloadDiag dialog = new DownloadDiag(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void changeButtonState() {
        download.addObserver(this);
        int status = download.getStatus();

        switch (status) {
            case Download.DOWNLOADING:
                OpenFolderButton.setEnabled(true);
                OpenButton.setEnabled(false);
                PauseButton.setEnabled(true);
                ResumeButton.setEnabled(false);
                CancelButton.setEnabled(true);
                break;
            case Download.PAUSED:
                OpenFolderButton.setEnabled(true);
                OpenButton.setEnabled(false);
                PauseButton.setEnabled(false);
                ResumeButton.setEnabled(true);
                CancelButton.setEnabled(true);
                break;
            case Download.ERROR:
                OpenFolderButton.setEnabled(false);
                OpenButton.setEnabled(false);
                PauseButton.setEnabled(false);
                ResumeButton.setEnabled(true);
                CancelButton.setEnabled(true);
                break;
            case Download.CANCELLED:
                OpenFolderButton.setEnabled(false);
                OpenButton.setEnabled(false);
                PauseButton.setEnabled(false);
                ResumeButton.setEnabled(false);
                CancelButton.setEnabled(false);
                break;
            default: // COMPLETE
                OpenFolderButton.setEnabled(true);
                OpenButton.setEnabled(true);
                PauseButton.setEnabled(false);
                ResumeButton.setEnabled(false);
                CancelButton.setEnabled(false);
        }

    }

    public void update(Observable o, Object arg) {    
        URLTextField.setText(download.getUrl());
        String Status = Download.STATUSES[download.getStatus()];
        StatusLabel.setText(Status);
        SizeLabel.setText(download.getFileSize());
        DownloadedLable.setText(download.getBytesDownloaded());
        SpeedLabel.setText(download.getDownloadSpeed());
        TimeLabel.setText(download.getRequiredTime());
        DownloadProgressBar.setValue((int) download.getDownloadProgress());
        changeButtonState();
    }

    /**
     * @return the download
     */
    public Download getDownload() {
        return download;
    }

    /**
     * @param download the download to set
     */
    public void setDownload(Download getdownload) {
        this.download = getdownload;
        download.addObserver(this);
        URLTextField.setText(download.getUrl());
        String Status = Download.STATUSES[download.getStatus()];
        StatusLabel.setText(Status);
        SizeLabel.setText(download.getFileSize());
        DownloadedLable.setText(download.getBytesDownloaded());
        SpeedLabel.setText(download.getDownloadSpeed());
        TimeLabel.setText(download.getRequiredTime());
        DownloadProgressBar.setValue((int) download.getDownloadProgress());
        changeButtonState();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JProgressBar DownloadProgressBar;
    private javax.swing.JLabel DownloadedLable;
    private javax.swing.JButton OpenButton;
    private javax.swing.JButton OpenFolderButton;
    private javax.swing.JButton PauseButton;
    private javax.swing.JButton ResumeButton;
    private javax.swing.JLabel SizeLabel;
    private javax.swing.JLabel SpeedLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JTextField URLTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
